
Currently Loaded Modules:
  1) intel/19.1.1   4) autotools/1.2   7) pmix/3.1.4     10) TACC
  2) impi/19.0.7    5) python3/3.7.0   8) hwloc/1.11.12
  3) git/2.24.1     6) cmake/3.16.1    9) xalt/2.10.2

 

2021-01-09 17:54:07.124640: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-01-09 17:54:07.149020: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2700000000 Hz
2021-01-09 17:54:07.149557: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x41a0a80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-09 17:54:07.149596: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-01-09 17:54:07.152973: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/apps/hwloc/1.11.12/lib:/opt/apps/pmix/3.1.4/lib:/opt/apps/intel19/python3/3.7.0/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib:/opt/intel/debugger_2020/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.1.217/linux/tbb/lib/intel64_lin/gcc4.8:/opt/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.1.217/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2020.1.217/linux/compiler/lib/intel64_lin:/opt/apps/gcc/8.3.0/lib64:/opt/apps/gcc/8.3.0/lib
2021-01-09 17:54:07.153003: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2021-01-09 17:54:07.153030: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c105-161.frontera.tacc.utexas.edu): /proc/driver/nvidia/version does not exist
Using TensorFlow backend.
/opt/apps/intel19/python3/3.7.0/lib/python3.7/site-packages/scipy-1.3.0-py3.7-linux-x86_64.egg/scipy/sparse/lil.py:504: FutureWarning: future versions will not create a writeable array from broadcast_array. Set the writable flag explicitly to avoid this warning.
  if not i.flags.writeable or i.dtype not in (np.int32, np.int64):
/opt/apps/intel19/python3/3.7.0/lib/python3.7/site-packages/scipy-1.3.0-py3.7-linux-x86_64.egg/scipy/sparse/lil.py:506: FutureWarning: future versions will not create a writeable array from broadcast_array. Set the writable flag explicitly to avoid this warning.
  if not j.flags.writeable or j.dtype not in (np.int32, np.int64):
WARNING:tensorflow:From /work/07913/xwu236/GVAE/2Citeseer_AE/3Deep_Layer36_AE_Feature.py:91: The name tf.sparse_placeholder is deprecated. Please use tf.compat.v1.sparse_placeholder instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/2Citeseer_AE/3Deep_Layer36_AE_Feature.py:94: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/model.py:82: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/initializations.py:26: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/layers.py:23: The name tf.sparse_retain is deprecated. Please use tf.sparse.retain instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/layers.py:83: The name tf.sparse_tensor_dense_matmul is deprecated. Please use tf.sparse.sparse_dense_matmul instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/layers.py:62: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/model.py:628: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/model.py:84: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/model.py:84: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/2Citeseer_AE/3Deep_Layer36_AE_Feature.py:150: The name tf.sparse_tensor_to_dense is deprecated. Please use tf.sparse.to_dense instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/optimizer.py:81: calling weighted_cross_entropy_with_logits (from tensorflow.python.ops.nn_impl) with targets is deprecated and will be removed in a future version.
Instructions for updating:
targets is deprecated, use labels instead
WARNING:tensorflow:From /work/07913/xwu236/GVAE/linear_gae/optimizer.py:83: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/2Citeseer_AE/3Deep_Layer36_AE_Feature.py:162: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /work/07913/xwu236/GVAE/2Citeseer_AE/3Deep_Layer36_AE_Feature.py:163: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

Traceback (most recent call last):
  File "/work/07913/xwu236/GVAE/2Citeseer_AE/3Deep_Layer36_AE_Feature.py", line 190, in <module>
    val_roc, val_ap = get_roc_score(val_edges, val_edges_false, emb)
  File "/work/07913/xwu236/GVAE/linear_gae/evaluation.py", line 23, in get_roc_score
    roc_score = roc_auc_score(labels_all, preds_all)
  File "/home1/07913/xwu236/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home1/07913/xwu236/.local/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 524, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "/home1/07913/xwu236/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home1/07913/xwu236/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 664, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home1/07913/xwu236/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
